server {
    listen 80;

    location = / {
        root /usr/share/nginx/html;
        try_files /signup.html =404;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/(news|auth|keywords) {
        resolver 127.0.0.11 valid=30s;
        set $upstream http://backend:8000;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
